from fastapi import FastAPI

app = FastAPI()


@app.get("/")
def read_root():
    return {"Hello world , Monitoring Date :24.03.2025 , All is  Ok ...."}


# dev1 is created,..........................

# dev1 codes,..........................
# dev1 codes,..........................
# dev1 codes,..........................
# dev1 codes,..........................
